### ISSUE TITLE
깃발 추가 완료 알람 깃발 색상

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#114]
## ![Screenshot_20230216-030846_daedongbread.jpg](https://user-images.githubusercontent.com/102673560/219612938-0a38aa98-5b2a-42cb-9a27-e6c4c94b6ee0.jpg)
![Screenshot_20230216-031121_daedongbread.jpg](https://user-images.githubusercontent.com/102673560/219612991-f5fbaef4-ec79-4151-9693-e8a5c2edf941.jpg)

알람 아이콘들이 살짝 디자인이 다르게 나옵니다   

## 진행 사항 

- [ ] todo_1

**Comment by KJoobin** [comment]
저장하기 바텀시트 에서 파란색 깃발로 저장을 하였는데, 알림에서는 주황색 으로 뜬다

알림 - 하트 색깔이 다르다.
