### ISSUE TITLE
홈지도>빵집선택했을때 바텀시트 높이 수정

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#116]
홈지도에서 떠있는 빵집 하나 선택했을때 바텀시트 고정영역 높이가 더 낮게 적용되어야할 것 같습니다 (현재위치에서재검색 버튼 떠있을때 높이와 동일하게)
![image](https://user-images.githubusercontent.com/104367595/219653531-22685990-72e7-4471-b2ba-c2087e933de0.png)

**Comment by KJoobin** [comment]
지도에서 빵집을 선택했을때, 바텀-시트의 높이에 고정을 갖는다. (초기값) 
선택된 빵집이 풀렸을때는 그전 상태값을 갖는다.
