### ISSUE TITLE
온보딩 이슈

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#119]
주빈님! 모션은 잘 나오는거같은데,
슬라이드할때 각 페이지가 고정이 안되어서 나와서,
조금씩 치우쳐지기도하고 3번째 슬라이드가 밀려서 4번째화면이 나온다던지 그러더라구용 ㅠㅠ,,
이부분 확인 해주실수있나요~??

그리고 혹쉬 온보딩 화면만 현재 디자인화면에 적용되어있는 나눔스퀘어폰트로 적용가능할까여~?? 
![image](https://user-images.githubusercontent.com/104367595/219657559-fbb5cc86-a91a-4138-9bd0-1472aef76c1e.png)

**Comment by TheMaraKing** [comment]
아직 이미지 중앙이 미세하게 안맞아요!!

**Comment by TheMaraKing** [comment]
![image](https://user-images.githubusercontent.com/102673560/230972542-fe92a0a5-84ac-4001-9af1-96cac6703040.png)
![image](https://user-images.githubusercontent.com/102673560/230972594-de1d8081-859c-46c7-b6e6-6ccc558ab831.png)
온보딩 2번째 3번째 페이지 중앙이 안맞는 것 같아요! 테스트 폰은 갤럭시 22, 아이폰 14 PRO 입니다.
