### ISSUE TITLE
리뷰 작성 > 그만두기 바텀 시트 오류 

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#123]
리뷰작성하다가 그만둘 때 바텀시트가 올라오는데, 
메뉴선택 이미지에서 올라오지 않아요! 여기서도 바텀시트가 올라오게 부탁드립니다~

![Screenshot_20230217-225108 (1)](https://user-images.githubusercontent.com/114842483/219676754-47e5be9c-6f3a-4636-b868-3fad4a675804.png)

**Comment by yunyeop** [comment]
@chi-eun  넵 알겠습니다 피그마로 확인했을때 다음 뎁스에서만 나오는 건줄 알고 저렇게 개발 했는데 
혹시 저 화면을 키자마자 x버튼을 눌러도 나와야 하나요?
예를들어 메뉴 하나라도 선택 했을때만 나온다던가 그런 작업이 필요 한가 해서요!

**Comment by chi-eun** [comment]
스토리보트에는 바텀시트가 모두 뜨기로 되어있는데, 리뷰 작성시 메뉴가 하나 이상 선택되었을 때부터 쭉 나와야할것같아요~! @yeeeena

**Comment by yunyeop** [comment]
@chi-eun  아 넵 알겠습니다~

**Comment by chi-eun** [comment]
@yunyeop 네!! 감사합니다! 윤엽님
