### ISSUE TITLE
홈 지도_선택완료 안눌리거나, 눌려도 깃발 안바뀌는 버그

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#127]
## ![Screenshot_20230216-030644_daedongbread.jpg](https://user-images.githubusercontent.com/102673560/219842649-7c68d3e8-c117-4522-9ea3-92517f524193.jpg)

깃발 리스트 변경이 안되는 것 같습니다   

## 진행 사항 

- [ ] todo_1

**Comment by KJoobin** [comment]
@TheMaraKing 해당이슈 조금만 더 자세히 적어주실수 있을까요?
