### ISSUE TITLE
상세페이지>리뷰작성 텍스트필드 오류

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#142]
1. 텍스트필드 디폴드일때 bg색상 gray-50, 라인 색상 gray-200으로 통일하였습니다.  사진업로드 입력 버튼도 마찬가지로 동일합니다!  
해당 색상 컬러 전체적인 입력필드에 적용 부탁드립니다!  빵집제보 메뉴명,가격 텍스트필드는 잘 적용되어있는 것 같습니다! 
사진업로드 입력 버튼도 동일하게 통일 시켜주세용!!  
사진업로드 입력 버튼은 디자인시스템 상에 select 영역에 등록되어있습니다!  참고 부탁드립니당~~
해당 부분 피그마 링크 공유드립니다!
https://www.figma.com/file/Y0rbvt5gXZtP1WUvS64uL7/DDS?node-id=6509%3A239534&t=YDZE5eLQ46KaIsok-4

2. 리뷰작성할때, 사진업로드 올려놓지 않은상태에서(빵평점, 상세한후기는 작성완료)  확인누르면 페이지 넘어가지 않는 오류가 있습니다.

![image](https://user-images.githubusercontent.com/104367595/221351924-8cb9445c-1ecf-4ad1-8529-32197dcb3e6d.png)

**Comment by yeeeena** [comment]
윤엽님 두개 이슈 아주 잘 해결되었는데용, 지금 사진업로드에서 빨간표시 되어있는 숫자부분 2/10 에서 '2'숫자쪽이 10보다 폰트사이즈가 작게 적용된거같아서용~!! 이부분 다시한번 확인가능하실까용~?ㅠㅠ 디테일한 부분인데 한번 체킹 부탁드려용~!!ㅠㅠ
![image](https://user-images.githubusercontent.com/104367595/222438215-045a1564-d132-4605-a153-92c1132dabee.png)

**Comment by yunyeop** [comment]
@yeeeena 바로 수정 했습니다! 확인 부탁드려요!

**Comment by yeeeena** [comment]
확인완료했습니다~!!
