### ISSUE TITLE
프로필 >저장목록

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#143]
저장목록에서 해당 아이콘 하트 크기가 이상합니다. 이부분 저희 디자인시스템 정리해놓은 페이지에 icon>map 영역에 색상별로 28x28사이즈로
정리되어있으니 여기서 export해서 참고 부탁드립니다~! 
아이콘 제대로 안뽑히면 저한테 export요청해주시면 제가 뽑아서 전달드리겠습니다~  혹시 몰라 해당 아이콘 있는 피그마 링크 전달드릴게요 https://www.figma.com/file/Y0rbvt5gXZtP1WUvS64uL7/DDS?node-id=6384%3A195231&t=YDZE5eLQ46KaIsok-4

![image](https://user-images.githubusercontent.com/104367595/221352003-60b0ae95-9f08-4aac-b432-987c85ce759a.png)

**Comment by yeeeena** [comment]
@baesumin 수민님! 아이콘상태는 좋은데여, 첨부한 사진보면은 아이콘 위에 아이콘이 겹쳐진거같아용,, 아이콘2개가 겹쳐진것처럼 보이네용 이부분 확인 부탁드리겠습니다 ( 그리고 혹시 추가로,,, 2숫자표시한 부분 보시면 빵캐릭터 일러스트가 좀 깨져있는데 ㅠㅠ,,,,,,, 혹시 4배수로 뽑아서 적용 가능하실까요?? 추출 어려우시면 제가 다운받아서 전달드릴게용!!)

![image](https://user-images.githubusercontent.com/104367595/222439247-1505fd05-d662-435a-b33e-c0c37fca1ff8.png)

**Comment by baesumin** [comment]
사진 수정했고 아이콘은 앱 지우고 다시 깔아서 확인 부탁드립니다.

**Comment by yeeeena** [comment]
@baesumin 어플 지웠다가 다시깔아봤는데 해당이슈 수정안되어있습니다 ㅠㅠ!!

![IMG_0041](https://user-images.githubusercontent.com/104367595/227204552-670b451c-0c91-4e64-b442-5e9cfd7f3134.PNG)
