### ISSUE TITLE
검색>빵집상세

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#146]
검색해서 들어온 빵집인데, 아직 뺑드미 상세 이외에 다른부분에는 적용되어있지 않는게 맞을까요? 
해당 페이지 개발오류가 맞는지 아닌지 몰라서, 일단은 오류로 인식하고 올려두겠습니다  .

메뉴가 하나도 등록되어 있지않는 경우는 없는게 맞는거졍~??   메뉴가 없는경우는 단순화면오류인지 개발오류인지 여쭤보고싶습니당~!!

그리고 리뷰가 한개도 없을때 화면이 개발적용되어있는지 잘 모르겠어서, 리뷰없을때 홈탭과 리뷰탭에서 나오는 화면 피그마 링크 공유드립니다.  https://www.figma.com/file/Y0rbvt5gXZtP1WUvS64uL7/DDS?node-id=6650%3A194667&t=YDZE5eLQ46KaIsok-4  

![image](https://user-images.githubusercontent.com/104367595/221352187-ca72963f-1715-4873-a5e3-0727b5494a32.png)
![image](https://user-images.githubusercontent.com/104367595/221352200-b4df99ec-5cc5-4737-8e0a-0b5b27505852.png)
![image](https://user-images.githubusercontent.com/104367595/221352205-fe377627-dff2-4b7f-a59c-d071b426380a.png)

**Comment by yunyeop** [comment]
메뉴가 안나오는건 실제 빵집에 데이터가 없어서 그렇습니당 나머지는 수정 했고 올려주신 피그마 링크쪽에 질문 코멘트도 하나 달아놓았는데 확인 부탁드려요!
