### ISSUE TITLE
프로필 > 프로필수정 텍스트필드 오류

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#150]
저번에 내용 전달드리긴했는데, 수정된 텍스트필드로 아직 적용안되어있는것 같습니당~!!
일단 오류사항으로 올려두도록 하겠습니다~

![image](https://user-images.githubusercontent.com/104367595/221352828-225d1f02-b779-4b0e-9c40-f3ff76f2d0f7.png)

**Comment by baesumin** [comment]
어떤부분을 고쳐야하는지 알 수 있을까요
