### ISSUE TITLE
빵집정보수정 >  장소삭제요청 > 사진찍기

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#153]
장소삭제요청에서 사진찍기버튼눌러 사진찍은후 화면에서 제출하기 버튼누르면 반응이 없습니다~!!

**Comment by baesumin** [comment]
방금 시뮬레이터,실제기기 2가지로 해보니 작동이 되는데 안되는 부분 영상으로 찍어주시면 감사하겠습니다

**Comment by yeeeena** [comment]
@baesumin 해당이슈 영상으로 전달드립니다!
https://user-images.githubusercontent.com/104367595/227206042-8f218af8-a15b-4b73-9201-a05d05e20655.MP4
