### ISSUE TITLE
프로필 로딩 지연 및 정보 불일치

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#158]
## 이번 버전 문제같은데요! 프로필 부분 지연되고 정보들이 안나오네요! ![Screenshot_20230226-154945_daedongbread.jpg](https://user-images.githubusercontent.com/102673560/221396740-73fc6092-de95-44bc-aba5-5576bd0cc0d2.jpg)

![Screenshot_20230226-155002_daedongbread.jpg](https://user-images.githubusercontent.com/102673560/221396743-b3142671-794f-46ef-b4de-93e25e2cee99.jpg)

![Screenshot_20230226-155012_daedongbread.jpg](https://user-images.githubusercontent.com/102673560/221396746-0cae4ce3-93dd-4c44-b044-017417314951.jpg)

 

## 진행 사항 

- [ ] todo_1

**Comment by baesumin** [comment]
api수정되어서 수정했습니다.
