### ISSUE TITLE
빵집 저장목록 상세 > 우측 더보기 클릭 시 

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#163]
마이 > 빵집 저장목록 > 우측 더보기 클릭 시 올라오는 바텀시트에  '저장목록 수정하기' / '저장목록 삭제하기' 두개가 나와야하는데 저장목록 삭제하기만 나와서 수정부탁드려요! 

![Screenshot_20230302-202930](https://user-images.githubusercontent.com/114842483/222417337-1c6bf6da-e5a8-482f-b944-afba94912362.png)
아래 디자인 이미지 참고 부탁드려요!
<img width="225" alt="스크린샷 2023-03-02 오후 8 34 10" src="https://user-images.githubusercontent.com/114842483/222417440-ae476347-e3f7-4180-ac09-c1e0422331ef.png">

**Comment by yunyeop** [comment]
@chi-eun 이부분은 수민님쪽 파트라 Assignees 변경 하겠습니다~

**Comment by chi-eun** [comment]
@yunyeop 네 감사합니다!
