### ISSUE TITLE
[ios] 프로필 수정 > 닉네임 

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#168]
[테스트폰 - 아이폰 12 미니 ]

1. 닉네임 수정 시 현재 영어가 불가하게 되어있습니다 (확인 버튼이 눌리지 않음) 
2. 맨 마지막 10번째 자리에 중성 / 종성이 입력이 되지 않는 경우가 있습니다!
     2-1. 한글 + 숫자 혼용 시 : 10번째 자리에 한글 초성만 입력됨 ('무서운바게트71얌'>'무서운바게트71ㅇ')
![IMG_2182](https://user-images.githubusercontent.com/114842483/222591818-340cc052-70f5-4b60-aaa6-03c0d5e5ee7d.PNG)
   2-2. 한글만 했을 때 : 10번째 자리에 중성까지입력되고 종성이 입력되지 않음 ('라라라라라라라라라옹' > '라라라라라라라라라오')

![IMG_2183](https://user-images.githubusercontent.com/114842483/222591967-05e6da9f-2fb9-42ce-b014-25d78e06932f.PNG)

3. 한글 자음 혹은 모음만 입력되거나 특수문자가 입력되었을 경우 다음과 같은 문구가 텍스트 필드 아래 노출되게 부탁드려요! 
1) 특수문자 입력 시(한글, 영문, 숫자 제외된 문자 입력 시) : 한글, 영문, 숫자만 사용 가능합니다.
2) 한글 자음 혹은 모음만 입력 시 : 닉네임을 확인해주세요.

**Comment by baesumin** [comment]
1. 제가 테스트했을때는 영어도 되서 서버로그쪽 확인 요청해야 할 것 같습니다.
2. 텍스트 입력 공통컴포넌트를 어떤분이 만드셨는지 몰라 혹시 중성/종성 처리 어떻게 가능한지 확인 부탁드립니다. @KJoobin @yunyeop 
3. 우선 서버쪽 구분이 안된것같아 '한글, 영문, 숫자만 사용 가능합니다.'로 수정하겠습니다.
