### ISSUE TITLE
[ios] 온보딩 그림자 그래픽 오류 

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#169]
테스트 폰 > 아이폰 12 미니 

온보딩 화면에서 그림자가 2번째 페이지에서는 네모 모양으로 깨지는 것 같고 3번째 페이지에는 말풍선 그림자가 아예 나오지 않습니다! 확인 부탁드려요! 감사합니당!!

[현재 온보딩 화면]
![IMG_2187](https://user-images.githubusercontent.com/114842483/222609941-c30a84a3-d116-41ca-b286-a2c49d8b683e.PNG)

![IMG_2188](https://user-images.githubusercontent.com/114842483/222609987-89db93f8-59db-47bd-874e-cfd1770ebec9.PNG)

**Comment by yunyeop** [comment]
이 부분은 주빈님과 예나님이 봐주시면 될것 같습니다! Assignees 변경 하겠습니다

**Comment by yeeeena** [comment]
@KJoobin 주빈님 이부분 확인부탁드릴게요~!!
