### ISSUE TITLE
삥집 제보 > 텍스트 입력중 닫기아이콘 눌러도 키보드가 안없어지는 현상

### ISSUE THREAD

**Issue by jellybrown** [daedongbread/bread-map-mobile#170]
- 기종: 아이폰 14 Pro Max
- 오류: 빵집 제보하는 화면
- 상황: 빵집이름 작성중, 오른쪽 상단 닫기 아이콘(X)을 누르면 키보드가 내려가고 확인팝업이 보여야 할 것 같은데, 키보드가 없어지지 않고 입력이 됩니다.
- 사진: 

<img src='https://user-images.githubusercontent.com/59910838/222610650-2f405bbf-06d6-4b69-99f9-bd33f14395c9.png' width='400px'/>
<img src='https://user-images.githubusercontent.com/59910838/222610664-2046190f-14dc-47f0-abf9-b3d397dd7c24.png' width='400px'/>

**Comment by yunyeop** [comment]
해당 이슈도 Assignees 변경 할게요~

**Comment by baesumin** [comment]
키보드 없어지게는 수정했는데 키보드 떠있는 상태로 닫아야 다른 버튼이 눌리는 부분은 다른분 혹시 해결방법 있는지 문의드립니다.

**Comment by yunyeop** [comment]
제 파트가 맞네요! ui가 비슷해서 착각 했습니다~

**Comment by TheMaraKing** [comment]
이슈 클로즈 하겠습니다!!
