### ISSUE TITLE
빵집 상세화면 > 빵집 정보 수정 > 텍스트 입력중 닫기아이콘 누르면 키보드만 내려가는 현상, 여백 넓어서 버튼 잘림

### ISSUE THREAD

**Issue by jellybrown** [daedongbread/bread-map-mobile#171]
- 기종: 아이폰 14 Pro Max
- 오류: 빵집 상세화면 > 정보 수정 글 작성
- 상황: 
  - 글 작성중에 닫기 아이콘 누르면 키보드만 내려감
  - 여백이 넓어서 버튼이 잘림 - 비슷한 이슈 #151
- 사진:
<img src='https://user-images.githubusercontent.com/59910838/222611947-3d09102c-1044-4abf-8742-57affeff7823.png' width='400' />
<img src='https://user-images.githubusercontent.com/59910838/222611958-0130c9ca-c1c0-4bfe-bfb4-7c58e5f04c38.png' width='400' />

**Comment by yunyeop** [comment]
@baesumin @jellybrown 수민님 파트라 Assignees 변경 하겠습니다~

**Comment by baesumin** [comment]
키보드 없어지게는 수정했는데 키보드 떠있는 상태로 닫아야 다른 버튼이 눌리는 부분은 다른분 혹시 해결방법 있는지 문의드립니다.
