### ISSUE TITLE
리뷰 작성 > 작성중 메뉴 선택 갯수 0개로 표시됨, 상단 그라데이션 안됨

### ISSUE THREAD

**Issue by jellybrown** [daedongbread/bread-map-mobile#172]
- 기종: 아이폰 14 Pro Max
- 오류: 빵집 상세화면 > 리뷰 작성
- 상황:
  - 메뉴 선택 갯수가 반영되지 않음 (5개 선택해도 0개)
  - 상단 선택된 메뉴들 보여주는 영역의 그라데이션이 먹히지 않음
- 사진:
<img src='https://user-images.githubusercontent.com/59910838/222614303-247420d3-f235-45ee-bc65-e67a7104d278.png' width='400' />

**Comment by yunyeop** [comment]
@jellybrown 
1. 우측 상단에 나오는 숫자 선택 갯수가 아니라 총 메뉴 목록 갯수입니다
2. 그라데이션 처리는 개발에서 어려울것 같아서 빼고 가는걸로 전에 정했습니다!
