### ISSUE TITLE
빵집 리뷰 > 좋아요 토글시 사진이 깜빡이는 현상

### ISSUE THREAD

**Issue by jellybrown** [daedongbread/bread-map-mobile#173]
- 기종: 아이폰 14 Pro Max
- 오류: 빵집 상세화면 > 리뷰 리스트
- 상황: 좋아요 토글시 사진이 깜빡이면서 리로드됨
사진:
<img src='https://user-images.githubusercontent.com/59910838/222614751-f3fc2bcd-5251-42d4-9718-6f3d14d1066a.png' width='400' />
<img src='https://user-images.githubusercontent.com/59910838/222614762-08a33a12-ac88-43bf-9853-f54aac52058c.png' width='400' />

**Comment by TheMaraKing** [comment]
이슈 클로즈 하겠습니다!!
