### ISSUE TITLE
저장목록 삭제

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#174]
## 저장목록 삭제가 안됩니다. 
![image](https://user-images.githubusercontent.com/102673560/222950192-c03f9ade-a58a-4c4d-89d9-b2eca0129cef.png) 확인이 안눌려요~ 

## 진행 사항 

- [ ] todo_1

**Comment by baesumin** [comment]
새로운  apk로 테스트 부탁드립니다.

**Comment by TheMaraKing** [comment]
수민님! 이거 [신중히] 단어가 위아래로 나누어져있는데요! "신"을 아래로 옮겨주실 수 있나요?

**Comment by baesumin** [comment]
수정했습니다.
