### ISSUE TITLE
프로필쪽 오류

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#176]
테스트폰: ios 12 미니
프로필쪽 저장목록 리스트 이름이 안뜨고, 아이콘에도 오류가 있습니다. 갑자기 프로필 사진도 같이 안뜨네용!
![image](https://user-images.githubusercontent.com/104367595/222961753-6fdf57b8-1d3c-415c-9faa-c8ed24898984.png)

**Comment by baesumin** [comment]
저장목록쪽은 apk 새로 받아서 확인하신건가요? 저는 문제없이 나오고 있습니다. 
프로필 사진도 저는 잘나와서 서버쪽에서 이미지 url을 내려주는지 로그 요청 부탁드리겠습니다.

**Comment by yeeeena** [comment]
@baesumin apk 새로 받아서 확인해봤는데도 리스트 아이콘 색상이 제대로 안뜨는 똑같은 오류가 있습니다! ㅠㅠ 프로필이미지는 잘 나옵니다!
![IMG_0039](https://user-images.githubusercontent.com/104367595/227203734-c1501491-a9ab-457f-b990-ededecbba50b.PNG)

**Comment by TheMaraKing** [comment]
저도 아이콘 색상 오류나요! ㅠㅠ
