### ISSUE TITLE
간단 디자인 / QA - 김주빈

### ISSUE THREAD

**Issue by KJoobin** [daedongbread/bread-map-mobile#179]
## 진행 사항 

- [x] [네비게이션바에 default아이콘 색상](https://w1631429446-yom224723.slack.com/archives/C02E25WKUA1/p1679574629512469)
- [x]  [상단 해더](https://w1631429446-yom224723.slack.com/archives/C02E25WKUA1/p1679617030147749)
- [x] [로그아웃](https://w1631429446-yom224723.slack.com/archives/C02E25WKUA1/p1679617030147749)
- [x] [홈 부분 즐겨찾기 기능](https://w1631429446-yom224723.slack.com/archives/C02E25WKUA1/p1679721057015229), #175
- [x] #177 
- [x] #169 (예나님께서 조금더 확인해주시기로 했습니다!)
- [ ] #166 
- [ ] #147 
- [x] #180 
- [x] #119 
- [x] #181 
- [ ] #182

**Comment by KJoobin** [comment]
네이게이션바에 default 아이콘 색상
[ffbe576f](https://github.com/daedongbread/bread-map-mobile/commit/ffbe576f9c23939bb1c80f3e09ad6d183e6a327f)

**Comment by KJoobin** [comment]
알림 페이지 뒤로가기
[2004d401](https://github.com/daedongbread/bread-map-mobile/commit/2004d401973f1130c24fb1700244534fd213d4fd)

**Comment by KJoobin** [comment]
상단 해더
[ac2f7abd](https://github.com/daedongbread/bread-map-mobile/commit/ac2f7abd6b622135c2057957daac22de82efdfea)

**Comment by KJoobin** [comment]
로그아웃
[8daf50d7](https://github.com/daedongbread/bread-map-mobile/commit/8daf50d7f60deb59c001a40924a518dc0efe6fad)

**Comment by yeeeena** [comment]
1. 지도홈에서 아이콘 깨짐현상
https://github.com/daedongbread/bread-map-mobile/issues/166

2. 홈지도에서 지도영역클릭시 바텀시트 영역 작아지도록 처리
https://github.com/daedongbread/bread-map-mobile/issues/147

이렇게 추가되면 될 것 같습니다~!!

**Comment by chi-eun** [comment]
1. 스플래쉬 이미지 변경 
#180 
이것도 추가되면 좋을 거 같아요~!

**Comment by KJoobin** [comment]
위에 2가지 테스크 추가 완료했습니다!

**Comment by KJoobin** [comment]
[ios] 온보딩 그림자 그래픽 오류 
[c2b442b4](https://github.com/daedongbread/bread-map-mobile/commit/c2b442b40d6064bd98d8524d41df232ae2803443)

**Comment by yeeeena** [comment]
@KJoobin 
https://github.com/daedongbread/bread-map-mobile/issues/181
주빈님 해당이슈도 한번 확인부탁드립니다~!!
