### ISSUE TITLE
영업시간 노출 오류

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#185]
영업시간 노출되는데 있어서, 통일이 이루어져야 할 것 같습니다.
현재 디자인상에는 한줄이 기본이고 옆에 드롭다운 버튼이있어서 드롭다운 버튼누르면 전체요일다 노출되는 형태입니다.

![IMG_0930](https://user-images.githubusercontent.com/104367595/230720263-55484e9b-529b-4265-b67d-30ddb4ff4357.PNG)

**Comment by TheMaraKing** [comment]
확인 완료
