### ISSUE TITLE
제보하기나 리뷰작성 등 이미지 작성 포함되어 있는 페이지 안넘어감 > 1순위로 이루어져야할듯

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#186]
사진업로드 포함되어있는 건 페이지 안넘어가는 오류
요 기능이 안되어서 QA안되는 화면이 많습니다! ㅠㅠ 1순위로 진행되어야할것같아요!

**Comment by TheMaraKing** [comment]
아직 용량이 클 경우 안넘어가는 것 같습니다!!

**Comment by TheMaraKing** [comment]
![image](https://user-images.githubusercontent.com/102673560/231643668-9c8b49d1-94c2-4501-98ed-2ca16f2490aa.png)아직 안넘어가는 것 같습니다..

**Comment by TheMaraKing** [comment]
안드로이드는 10장 업로드 되고 ios는 9장 이상은 안됩니다
