### ISSUE TITLE
프로필화면 오류

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#192]
1. 텍스트 두께 다름 > body1 bold로 변경
2. 닉네임이랑 팔로잉텍스트 사이에 여백 현재는 너무 좁아보임  4px여백으로 맞춰주세요
3. 프로필 디폴트 이미지 네모난 형태인데 원형으로 되어있음
4. 저장된 장소 3개 넘어가는 경우에 추가적으로 횟수 표시되어야함(현재 표시안됨) - 예를들어, 가고싶어요에 5개를 저장하면
+2 텍스트가 붙어야함

![image](https://user-images.githubusercontent.com/104367595/230721032-f60c4e92-0b37-49a9-8b5a-08adbda1ece6.png)

**Comment by baesumin** [comment]
@yeeeena 
3번 같은 경우 프로필 디폴트 이미지가 원형으로 되어있습니다.
https://d1li9vlpohb8oz.cloudfront.net/defaultImage/defaultUser.png

**Comment by TheMaraKing** [comment]
아이폰에서 2번 이슈 아직 발생하고있습니다!

**Comment by baesumin** [comment]
수정했습니다

**Comment by yeeeena** [comment]
간격 너무 넓게 설정되어있습니다! ㅠㅠ 오른쪽화면 리뷰쪽에 있는 간격이랑 맞춰주세여!

![image](https://user-images.githubusercontent.com/104367595/231146054-868227ad-b9fd-4955-938b-f0b3490b7db0.png)

**Comment by yeeeena** [comment]
프로필 저장목록 사진위에 dim처리 그레이톤으로 되어있는데, 컬러값 #000000의 opacity 40%로 맞춰주세요!

![image](https://user-images.githubusercontent.com/104367595/231146691-74e4dc3f-3792-4dbd-b768-05bb13563f13.png)

**Comment by TheMaraKing** [comment]
예나님 이거는 예나님이 확인 후 닫아주세요~~
