### ISSUE TITLE
[빵집상세] 저장됨 한번 더 클릭 시 저장 해지 기능 오류 

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#201]
빵집 저장됨 한번 더 눌렀을 때 저장 해지가 되어야하는 데 작동하지 않습니다 ~! 

![스크린샷 2023-04-09 오후 10 08 53](https://user-images.githubusercontent.com/114842483/230774488-0baaae29-576c-42a7-bcb9-a0f7e25ce232.png)

**Comment by baesumin** [comment]
수정했습니다.

**Comment by chi-eun** [comment]
감사합니다~!

**Comment by TheMaraKing** [comment]
![image](https://user-images.githubusercontent.com/102673560/230934236-47e316c5-d9b3-4ade-9bb5-2a7412e42d60.png) 수민님 요거 저장하기 누르자 마자 해지는 아니구 첨부드린 사진처럼 돼야합니다!! (이렇게 안되면 지도 부분에서 삭제가 불가능해집니다!)
