### ISSUE TITLE
활동 알림 켜고 뒤로가기 하고 다시 설정 들어오면 꺼져있어용

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#213]
## 진행 사항 

- [ ] todo_1

**Comment by TheMaraKing** [comment]
아직 안됩니다!!.. 재확인 부탁드려요

**Comment by TheMaraKing** [comment]
안드로이드는 되고 ios는 아직 안됩니다

**Comment by yeeeena** [comment]
@TheMaraKing 확인했습니다! 전 잘됩니다! 윤기님 요부분 한번더 확인해주세요!

**Comment by TheMaraKing** [comment]
네 일단 켜져서 닫을게요!! 아직 조금 이슈가 있긴 해보이는데 이건 다시 이유 올리겠습니다~
