### ISSUE TITLE
프로필 사진 변경이 안됩니다. ios, 안드로이드 동일 (4.9 QA 15)

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#216]
## 진행 사항 

- [ ] todo_1

**Comment by TheMaraKing** [comment]
수민님! 프로필 바뀌긴 동작 하긴하는데요~ 그 다음 마이페이지에서 사진 부분 공란으로 나오고, 수정 들어가면 디폴트 이미지로 나오고있습니다! (Ios)

**Comment by TheMaraKing** [comment]
수민님! 프로필 바뀌긴 동작 하긴하는데요~ 그 다음 마이페이지에서 사진 부분 공란으로 나오고, 수정 들어가면 디폴트 이미지로 나오고있습니다! (Ios)

**Comment by TheMaraKing** [comment]
안드로이드도 같은 현상 일어납니다

**Comment by baesumin** [comment]
@grand7070 시뮬레이터상으로는 정상적으로 동작하는데 실제 기기에서 어떤지 서버 로그확인 부탁드립니다!

**Comment by grand7070** [comment]
DB에 확인해보니까 undefined이라는 값으로 올라와있습니다. 이미지 업로드 API 엔드포인트가 //v1/images로 호출되어서 생기는 문제 같습니다

**Comment by grand7070** [comment]
@baesumin DB에 확인해보니까 undefined이라는 값으로 올라와있습니다. 이미지 업로드 API 엔드포인트가 //v1/images로 호출되어서 생기는 문제 같습니다

**Comment by yunyeop** [comment]
해결 완료 했습니다!
