### ISSUE TITLE
현재 앱이 켜두고 5~10분 지나면 데이터를 불러오지 않는 경우가 많습니다.

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#219]
## 현재 앱이 켜두고 5~10분 지나면 대부분 동작에서 반응이 없습니다. (홈 지도에서 위치 이동 후 "현위치에서 검색", "내 프로필" 들어가기 등)
프론트 이슈인지, 백엔드 이슈인지 잘 모르겠네요! 

-- 기능에 대한 간단한 설명 작성 -->

## 진행 사항 

- [ ] todo_1

**Comment by yeeeena** [comment]
저도 동일한 이슈 있습니다!
