### ISSUE TITLE
[프로필] 리뷰에서 마이 프로필 유입 시 > 팔로우 버튼 수정으로 변경 

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#224]
둘다 내 프로필인데, gnb로 들어갔을 때랑 댓글에서 들어갔을 때랑 달라요!  리뷰에서 마이 프로필 유입 시 > 팔로우 버튼 수정으로 변경되어야 합니다 
![스크린샷 2023-04-12 오후 9 11 43](https://user-images.githubusercontent.com/114842483/231453129-d9ae4957-217d-453f-b788-f6938e12e282.png)

**Comment by yeeeena** [comment]
@chi-eun 치은님 요것도 제가 확인했어요~~~!!
