### ISSUE TITLE
[홈] 리뷰 텍스트가 백그라운드 영역 밖으로 삐져나와요 

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#225]
리뷰 텍스트가 백그라운드 영역 밖으로 삐져나와요 
![스크린샷 2023-04-12 오후 9 13 45](https://user-images.githubusercontent.com/114842483/231453689-1b26fcf1-59b8-4e4b-aefa-642203cf0744.png)

**Comment by yeeeena** [comment]
@chi-eun 치은님 요거 제가 확인했습니다~!! 정상적으로 나옵니다
