### ISSUE TITLE
[한글 오류] 웻즐프레즐에서 '웻' > '??'로 나오는 거 같아요

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#227]
한글 오류는 어느 분을 어사인해야할지 몰라..수호님도 어사인 같이 드렸어요~! 

![IMG_3821](https://user-images.githubusercontent.com/114842483/231454397-06f576b1-d968-49f7-bad6-48d2a0971429.PNG)

**Comment by grand7070** [comment]
음 DB에는 웻으로 잘 들어가있습니다

**Comment by KJoobin** [comment]
제 핸드폰으로는 웻으로 잘 나오네요..!

**Comment by TheMaraKing** [comment]
저도 잘 나오는 것 같아요! 클로즈 하겠습니다
