### ISSUE TITLE
홈>마커 현위치에서 검색 안됨

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#50]
![image](https://user-images.githubusercontent.com/102673560/195152833-ba8f13f4-ca3a-458f-98ec-342ae26758f1.png)

1. 빵집 현위치에서 검색 안됨...
2. 인기순으로 변경시 사라짐!
3. 그리고 다시 안생김...

수정 부탁드립니다~!

**Comment by KJoobin** [comment]
@TheMaraKing 

> 빵집 현위치에서 검색 안됨... 

좀더 자세하게 말씀해주실수 있을까요 ??
