### ISSUE TITLE
리뷰>메뉴 직접입력하기 

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#51]
![image](https://user-images.githubusercontent.com/102673560/195153513-445fae53-54e9-49eb-a73a-2d5766f18e3f.png)

1. 같은 이름 빵이 추가됩니다

향후 API 연결시, 이미 등록된 빵일 경우 이미 등록된 빵이라고 나와야 할 것 같습니다!

**Comment by yunyeop** [comment]
확인해 보고 코멘트 남기겠습니다!
