### ISSUE TITLE
리뷰>리뷰 작성

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#52]
![image](https://user-images.githubusercontent.com/102673560/195153869-124a0c53-68c1-428c-95f3-c43395106eeb.png)

1. 글씨 화면 겹침
2. 별점 등록 불가
3. 해당 글씨는 처음부터 표시 X, 10글자 입력 안하고 확인 눌렀을 때 뜨게 변경
4. 후기 작성시 확인 버튼이 위로 올라와서 무의식 적으로 사진 입력 안하고 확인 버튼을 누르면 리뷰작성 완료됨...
5. 사진 혹시 한번에 여러장 추가는 안되나요?

**Comment by yunyeop** [comment]
@TheMaraKing 사진 등록 안하면 리뷰 못 올리는게 맞는거죵?

**Comment by yunyeop** [comment]
@TheMaraKing 제가 확인 하기로는 여러장 업로드가 가능 한데 혹시 캡쳐본 있을까요??

**Comment by TheMaraKing** [comment]
@yunyeop 사진 없이 가능합니다!

**Comment by TheMaraKing** [comment]
![IMG_9126](https://user-images.githubusercontent.com/102673560/196481403-f0ccedbb-be81-40e7-8a24-7069cba53f68.JPG)
![IMG_9127](https://user-images.githubusercontent.com/102673560/196481415-bd3d1117-1df4-4e5d-91c0-b4b891de3a31.JPG)
![IMG_9128](https://user-images.githubusercontent.com/102673560/196481418-9c81135b-23f3-4256-90f1-49a52880f6cc.JPG)
@yunyeop 이렇게 한장한장 추가해야합니다!!··· 기존은 s21입니다
