### ISSUE TITLE
폰트오류

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#70]
![image](https://user-images.githubusercontent.com/104367595/211561169-af36f7ea-07e6-4296-8848-0daa5a7ee9c4.png)

현재 앱에 나오는 전체적인 폰트가 저희가 설정해놓은 노토산스 폰트가 아니라
기본폰트인거 같은데 노토산스로 폰트 전체변경 가능한가요?

그리고 표시해놓은 곳도 검정색으로 나와야하는데 색상이 다르게 나옵니다.

**Comment by KJoobin** [comment]
숫자는(Number n) - Spoqa Han Sans Neo

**Comment by yeeeena** [comment]
@KJoobin 주빈님 아직 전체적으로 폰트 수정 적용안된 부분이 많은 것 같은뎅, 전체화면 폰트 수정 언제 완료될까용~??
