### ISSUE TITLE
스플래쉬 화면 크기 확인 요청

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#71]
![image](https://user-images.githubusercontent.com/104367595/211562555-169c81ef-a979-486e-b7d8-542d1ebded4f.png)

디자인 진행하면서 아이폰에서 미러링하면서 확인한 디자인보다
가운데 일러스트와 하단에 버튼들이 크게 느껴지는데,
혹시 이게 테스트폰마다 크기가 커지면서 비율에따라서 버튼이나 일러스트도 동일하게 커지나요?

그리고 구글계정으로 로그인버튼하고, 카카오계정으로 로그인버튼이 디자인된 시안과 다르게 보입니다! 텍스트도 색상이 다르고, 버튼색상, 아이콘이 다르게 표시되어있습니다!

아이폰으로 미러링해서 보았을때의 디자인시안 첨부합니다.
![image](https://user-images.githubusercontent.com/104367595/211563039-c9bcca86-c576-423d-b3aa-63b0ca26497b.png)

**Comment by KJoobin** [comment]
> 혹시 이게 테스트폰마다 크기가 커지면서 비율에따라서 버튼이나 일러스트도 동일하게 커지나요?

버튼의경우 사이즈에 따라서 커지는거 같아보입니다. 관련해서 수정하고 노티드릴게요!

**Comment by yeeeena** [comment]
넴 감사합니다!

**Comment by yeeeena** [comment]
@KJoobin 주빈님 이부분 아직 해결 안되었을까용~?ㅠㅠ 그리고 카카오계정 로그인버튼도 고유색상(노란색)이랑 로고로 쓰여야 하는데 이부분도 적용이 안되어있어서요!!ㅠㅠ (카카오계정인데 애플로고로 들어가있어영)
