### ISSUE TITLE
프로필 - 저장목록 카운팅 오류

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#76]
## 저장목록의 카운팅 기준은 빵집입니다! 현재 카테고리 수로 되어있는 것 같아요! 현재 0으로 표시되어야 할 것 같습니다. 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/102673560/211885297-4935f211-27b8-429f-8a50-fdb0e77d85e6.png">

## 진행 사항 

- [ ] todo_1

**Comment by baesumin** [comment]
@grand7070  수호님 변경 부탁드립니다.

**Comment by baesumin** [comment]
@TheMaraKing 저장목록의 카운팅 기준은 빵집이라는 부분이 '가고싶어요'에 저장된 빵집이 5개, '가봤어요'에 저장된 빵집이 2개면 '저장목록 7'이라고 나오면 되나요?

**Comment by TheMaraKing** [comment]
조금 어려워보일 수도 있을 것 같아서 디자이너분들이랑 이야기 해볼게요! 잠시 홀딩해주세오!!

**Comment by TheMaraKing** [comment]
수민님 이 부분은 수정 안하고 지금 기능 유지할게요!

**Comment by TheMaraKing** [comment]
완료
