### ISSUE TITLE
기본 마커 오류 수정 요청 (하트 -> 빵 모양 아이콘)

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#84]
## 현재 마커들이 잘못 표시되고있어 수정요청드립니다. 

1. 기본 마커 : 하트 -> 빵 모양 아이콘으로 변경

-현재 화면-
<img width="330" alt="image" src="https://user-images.githubusercontent.com/102673560/212699455-d9081c6d-551e-4bdb-b613-c0a48abf2c0f.png">

-변경 요청 아이콘-
![image](https://user-images.githubusercontent.com/102673560/212699100-073cbc38-6c6b-4f51-b846-5fd0bfe5593d.png)

## 진행 사항 

- [ ] todo_1

**Comment by grand7070** [comment]
백에서는 따로 모양을 내려주지 않고 있습니다

**Comment by TheMaraKing** [comment]
@grand7070 넵 알겠습니다!! @KJoobin 이것도 확인 부탁드려요~~
