### ISSUE TITLE
홈_깃발 활성화시 기본 마커 오류

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#86]
## 홈 지도에서 깃발 활성화시 나오는 마커의 수정요청드립니다! 
주황색 하트 -> 그래이 빵모양

-현재 화면-
<img width="338" alt="image" src="https://user-images.githubusercontent.com/102673560/212700443-f99c587c-b384-4f14-81b4-4f2feb94c406.png">

-수정 화면-
![image](https://user-images.githubusercontent.com/102673560/212700498-5a193f5a-a1e2-4a5d-be90-42a1a4088c3f.png)

## 진행 사항 

- [ ] 깃발 활성화시 기본 마커 변경

**Comment by grand7070** [comment]
백에서는 해당 빵집이 유저의 깃발 리스트 안에 포함되지 않을시 GRAY로 내려주고 있습니다

**Comment by TheMaraKing** [comment]
@grand7070 넵!!! @KJoobin 주빈님 프론트에서 해결 가능한거죵?!
