### ISSUE TITLE
저장 목록 이미지 오류

### ISSUE THREAD

**Issue by TheMaraKing** [daedongbread/bread-map-mobile#88]
## 저장 목록 이미지에 오류가 있습니다. (이전 버전에서는 잘 보였던 것 같은데 이상하네요!) 

-현재 화면1 : 추가되지 않았을 경우-
<img width="340" alt="image" src="https://user-images.githubusercontent.com/102673560/212701401-36cce64e-4173-4d5c-b35b-0ae1924bf5e1.png">

- 현재 화면2 : 빵집이 추가 된 경우 / "가봤어요"와 "강남빵집" 리스트에 2개씩 추가했는데 이렇게 나오네요! -
<img width="340" alt="image" src="https://user-images.githubusercontent.com/102673560/212701577-1a1f59d5-6bb9-48ee-a0cd-ca32652a3884.png">

들어갔을 경우에는 오류 없습니다!
<img width="338" alt="image" src="https://user-images.githubusercontent.com/102673560/212701800-f9cae661-248f-42c8-a9b4-5ddee0dac7f8.png">

## 진행 사항 

- [ ] 추가되지 않았을 경우
- [ ]  빵집이 추가 된 경우

**Comment by baesumin** [comment]
빵집을 추가했을때 이미지를 안넣어서 그런것같습니다.
이미지가 없으면 서버에서 따로 이미지를 내려주지 않습니다.
이미지를 안넣더라도 기본 이미지가 있어야 하는 경우 서버쪽에서 기본 이미지 url을 내려줘야 할 것 같습니다.

**Comment by TheMaraKing** [comment]
@baesumin 아하 넵 알겠습니다. 이 부분은 디자이너 분들이랑도 이야기를 해봐야겠네요!!··· @chi-eun @yeeeena 이 부분 이미지 없을 경우 어떻게 띄울지 고민해보죠!!
