### ISSUE TITLE
feat: 빵집 상세페이지 2차 구현

### ISSUE THREAD

**Issue by jellybrown** [daedongbread/bread-map-mobile#9]
## 개요 
- 네비게이션 홈 화면에서만 위치 다르게 조정할 수 있는지 체크
- 기존 뼈대만 잡은 상세페이지를 디테일하게 구현
- 리뷰페이지에 추가된 댓글화면 구현
- 추후 다른파트 맡은분들이 제보, 바텀시트 완성하면 상세페이지와 연결되는 제보화면, 깃발 바텀시트 구현 예정
## 진행 사항 

- [ ] 상세페이지 UI 디테일 잡기
- [ ] 리뷰페이지 상세

**Comment by yunyeop** [comment]
@jellybrown 유진님! 다른 해당 이슈는 닫겠습니다!
