### ISSUE TITLE
리스트 수정/삭제 

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#93]
저장목록 들어갔을 때 
수정 / 삭제가 잘 구동되지 않아요
![1A036164-A656-4EEF-92BA-EFD91C75B405](https://user-images.githubusercontent.com/114842483/214229642-3dcae7e7-def7-4cec-ad18-80ed76401b3b.jpeg)

1. 수정눌렀을 때 기존 저장되어있는 텍스트가 적혀있어야할거같아요 (ex 제가 예시로  ‘뉴리스트’를 만들었으면 뉴리스트가 적혀있고 사용자가 그걸 지우고 목록명을 수정하도록)
![061EB7B2-E81D-49E8-BD48-455C4E9EA7E6](https://user-images.githubusercontent.com/114842483/214229661-420a47f0-625c-402f-8b12-540c5140f56f.png)

2. 삭제를 눌렀을 때 목록이 삭제되지 않습니다!

**Comment by baesumin** [comment]
수정 후 말씀드리겠습니다.
