### ISSUE TITLE
이미 빵집 목록에 저장되어있는 빵집 눌렀을 때 바텀시트

### ISSUE THREAD

**Issue by chi-eun** [daedongbread/bread-map-mobile#94]
이미 빵집 목록에 저장되어 있는 빵집 > 눌러 수정할때

1.사진 내 1이라고 되어있는곳에 빵집 명(폴몬트마카롱)이 들어가야합니다

2. 바텀시트에 새로 추가한 ‘뉴리스트’가 초록색 깃발 아이콘 > 초록색 하트 아이콘으로 수정되어야합니다!

3.이미 뉴리스트라는 곳에 저장되어있던 곳을 수정하는 바텀시트라, 뉴리스트에 체크가 되어있어야합니다!

4. 다른 리스트(가고싶어요) 체크 후 완료 시 해당 리스트로 이동되어야합니다!

감사합니다~
![8BB5056A-2DDD-4497-B9CA-C17D17EF1C8D](https://user-images.githubusercontent.com/114842483/214231560-77a1616d-3bc9-492d-8b2c-04ea3afd3133.jpeg)

**Comment by baesumin** [comment]
1. 수정되어있는데 앱 삭제 후 새로 받아서 확인해보시면 될 것 같습니다.
2. 확인 후 수정하겠습니다.
3. @KJoobin 확인부탁드립니다.
4. 1과 동일하게 수정되어있습니다.

**Comment by chi-eun** [comment]
3. 네 동일하게 해주시면 됩니다! 감사합니다
