### ISSUE TITLE
상세페이지>홈 여백조정

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#95]
![image](https://user-images.githubusercontent.com/104367595/214780663-4fbf58e5-a62d-454a-91a9-ab69355d19d3.png)

빵집명과 밑에 여백이 너무 넓습니다. 디자인 상에 나와있는 수치대로 수정부탁드립니다!

디자인 예시 이미지도 첨부드립니다.
![image](https://user-images.githubusercontent.com/104367595/214780891-967bcf70-fed6-4d67-98e1-3a09724a9cd2.png)

**Comment by yunyeop** [comment]
넵 수정 했습니다~
