### ISSUE TITLE
상세페이지 > 홈 빵메뉴 이미지 

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#96]
![image](https://user-images.githubusercontent.com/104367595/214781248-f490c412-786b-4d81-ae9d-61cfed091c29.png)

빵메뉴 이미지들이 없을때는 아예 안나오는걸로 알고 있는데, 임시로 이미지를 넣어놓으신건가여~? 따로 이미지가 없을때는 아예 안뜨도록 따로 처리 되어있을까요~??

**Comment by yunyeop** [comment]
확인해보니 현재는 저장된 이미지 값과 상관없이 저기 보이는 임시 이미지만 보이는것 같습니다! 이부분 수정 하겠습니다~

**Comment by yunyeop** [comment]
해당 메뉴 탭 작업에서 한번에 보여드려도 될까요?

**Comment by yeeeena** [comment]
넵!! 그때 다시 확인하도록 하겠습니다~ :) 그럼 일단 해당이슈는 클로즈 하겠습니다~
