### ISSUE TITLE
상세페에지 > 홈 > 리뷰

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#97]
![image](https://user-images.githubusercontent.com/104367595/214781585-102b62fd-0ea8-4be5-b912-597f0ef01df0.png)

리뷰 빵메뉴 태그들이 최대1줄로 쭉 세로로 나열되고, 슬라이드 되는 형태였으면 합니다 (빵메뉴태그들이 많아지면서 밑으로 떨어지면 정작 중요한 리뷰내용들이 잘 안보일 것 같아서요~) - 디자인 시안 참고 부탁드립니다!
그리고 현재 폰트때문인지 뭔지 태그들의 폰트가 좀 커보이는데, 이부분 확인 부탁드립니다! (디자인상에서는 태그들의 폰트사이즈 12, 본문사이즈 14입니다)

그리고 혹시 리뷰에서 이미지들도 같이 보여질때도 하나 예시로 띄어주실수있으실까요~? :)

**Comment by yunyeop** [comment]
폰트 사이즈는 정상적으로 적용 되어 있는데 아마 폰트 문제로 보이구요! 나머지 이슈는 수정 완료 했습니다! 이미지도 아래로 내려 보시면 보일거에요!

**Comment by yeeeena** [comment]
네~ 1) 태그 슬라이드되는 형태와 2) 리뷰에 이미지 있는경우 확인완료하였습니다! 폰트문제 해결되면 태그 폰트사이즈 확인후에 이슈 클로즈 하겠습니다~ :)

**Comment by yunyeop** [comment]
> 네~ 1) 태그 슬라이드되는 형태와 2) 리뷰에 이미지 있는경우 확인완료하였습니다! 폰트문제 해결되면 태그 폰트사이즈 확인후에 이슈 클로즈 하겠습니다~ :)

폰트 이슈는 주빈님이 다른 issue에서 다루실것 같은데 그쪽에서 확인 하시면 어떨까요? 나중에 두번 일 하실까봐요!

**Comment by yeeeena** [comment]
네넹 그럼 이부분 클로즈 이슈하겠습니다~~~!!
