### ISSUE TITLE
상세페이지 > 메뉴 > 빵메뉴 제보하기

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#98]
![image](https://user-images.githubusercontent.com/104367595/214782482-1b4ada60-70c2-40fb-b263-b383b6d9c247.png)

이부분은 홈쪽아니고 빵메뉴 제보하기쪽인데, 다른부분 미완성된 부분도 올려달라하셔서 이슈등록합니다!

1) 처음에 들어가자마자 텍스트필드 밑에 오류텍스트가 뜹니다. 첫 화면 디자인 따로 해둔게 있어서 그 화면 참고 부탁드립니다! (오류텍스트는 아무것도 입력안하고 확인버튼 눌렀을때만 뜨도록)

2) 사진입력 영역이 왼쪽에 너무 붙어있습니다. 왼쪽 여백 확인 부탁드립니다.

**Comment by yeeeena** [comment]
@yunyeop 윤엽님! 여기페이지는 아직 수정 안된거죵~??

**Comment by yunyeop** [comment]
> @yunyeop 윤엽님! 여기페이지는 아직 수정 안된거죵~??

네 맞습니다! slack에 apk 전달 드릴때 미완인 부분 같이 적어놨습니다!

**Comment by yeeeena** [comment]
@yunyeop 넵~!! 추후에 재확인하겠습니다~
