### ISSUE TITLE
상세페이지 > 정보쪽 업데이트 필요

### ISSUE THREAD

**Issue by yeeeena** [daedongbread/bread-map-mobile#99]
![image](https://user-images.githubusercontent.com/104367595/214783292-d31f27e4-f9d3-43f7-affc-0113c45e9006.png)

시설정보쪽 아이콘들과 추가된 항목(택배,예약)들 변동사항이 있는데 이부분 업데이트가 안된것같습니다.
혹시몰라 업데이트된 디자인 시안도 같이 첨부해드리겠습니다.

![image](https://user-images.githubusercontent.com/104367595/214783470-4d72b4c1-bd61-49b8-b409-0da3540b03eb.png)

**Comment by yeeeena** [comment]
@yunyeop 윤엽님~ 혹시 체크되어있는것도 같이 확인 가능하도록 해주실수있나용~?

**Comment by yunyeop** [comment]
> 

혹시 캡쳐 이미지로 보여드려도 될까요?

**Comment by yeeeena** [comment]
@yunyeop  아네넹 좋습니당 확인완료했습니다~~ 이슈 클로즈할게여~!!
